export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Intro } from './Intro';
export { default as Match } from './Match';
export { default as Profile } from './Profile';
export { default as Signup } from './Signup';
export { default as SOS } from './SOS';
export { default as Chat } from './Chat';
export { default as ChatDetail } from './ChatDetail';
